COUNTRY_NAME_TO_CODE = {
    "Italy": "ITA",
    "France": "FRA",
    "Switzerland": "SUI",
    "Iceland": "ISL",
    "Ukraine": "UKR",
    "Finland": "FIN",
    "Malta": "MLT",
    "Lithuania": "LTU",
    "Russia": "RUS",
    "Greece": "GRE",
    "Bulgaria": "BUL",
    "Portugal": "POR",
    "Moldova": "MDA",
    "Sweden": "SWE",
    "Serbia": "SRB",
    "Cyprus": "CYP",
    "Israel": "ISR",
    "Norway": "NOR",
    "Belgium": "BEL",
    "Azerbaijan": "AZE",
    "Albania": "ALB",
    "San Marino": "SMR",
    "Netherlands": "NED",
    "Spain": "ESP",
    "Germany": "GER",
    "United Kingdom": "GBR",
    "Croatia": "CRO",
    "Romania": "ROU",
    "Denmark": "DEN",
    "Austria": "AUT",
    "Estonia": "EST",
    "Slovenia": "SLO",
    "Poland": "POL",
    "Australia": "AUS",
    "North Macedonia": "MKD",
    "Czech Republic": "CZE",
    "Ireland": "IRL",
    "Georgia": "GEO",
    "Latvia": "LAT",
    "Belarus": "BLR",
    "Hungary": "HUN",
    "Armenia": "ARM",
    "Montenegro": "MNE",
    "Bosnia & Herzegovina": "BIH",
}


BIG_FIVE = ["Spain", "Germany", "Italy", "France", "United Kingdom"]

SCRAPING_BASE_URL = "https://eurovisionworld.com/eurovision/"