name: Python application

on:
  push:
    branches:
      - '*'

jobs:
  python-tests:
    runs-on: ubuntu-latest

    env:
      TEST_POSTGRES_USER: ${{ secrets.TEST_DB_USER }}
      TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_DB_PASSWORD }}
      TEST_POSTGRES_DB: ${{ secrets.TEST_DB_NAME }}
      TEST_POSTGRES_PORT: ${{ secrets.TEST_DB_PORT }}
      TEST_POSTGRES_SERVER: ${{ secrets.TEST_DB_SERVER }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}

    services:
      postgres:
        image: postgres:14.2
        env:
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Chrome WebDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver

    - name: Create test role in PostgreSQL
      run: |
        psql -h $TEST_POSTGRES_SERVER -p $TEST_POSTGRES_PORT -U postgres -c "CREATE ROLE $TEST_POSTGRES_USER SUPERUSER CREATEDB LOGIN PASSWORD $TEST_POSTGRES_PASSWORD;"

    - name: Run tests
      run: |
        if pytest --collect-only | grep "collected 0 items"; then
          echo "No tests to run"
        else
          pytest
        fi
